### ISSUE TITLE
CORS Error 

### ISSUE THREAD

**Issue by StefanVesper** [Accudio/async-alpine#21]
Hey there! 

First of all thanks for this repo! 
I tried it out but I always run into the same issue : 

async-alpine.script.js:1 Uncaught (in promise) TypeError: Failed to resolve module specifier 'myComponent.js'. The base URL is about:blank because import() is called from a CORS-cross-origin script.

The myComponent.js file is in a public folder and uses your example code from the readme. 

Is this happening because I am loading your script via cdn? 

I am using the cdn-link from the readme. 

And, btw, will there be a cdn link for the new beta?

**Comment by Accudio** [comment]
@StefanVesper I've added a fix in the latest commit of the `0.4-rebuild` branch which should fix your issue, and will be out in version 0.4. If you want to test it then please do, you can use Rawgit for the CDN URL.

When a relative URL was being used in `ax-load-src` and Async Alpine was being loaded from a different origin it was resolving against that one instead of the document as was expected. I've tweaked it so that whenever a relative URL is used it is converted to an absolute URL with the base of the document origin which I think is more expected behaviour.
